"""模型解锁 workbench 补丁标记（与 model_unlock 逻辑解耦，避免循环 import）。"""

MARKER_MODEL = "/*MODEL_UNLOCK_V1*/"
MARKER_MEM = "/*MODEL_MEM_PRO_V1*/"
MARKER_MAX = "/*MODEL_MAXMODE_V1*/"
MARKER_FETCH = "/*MODEL_MEMBERSHIP_SPOOF_V1*/"
MARKER_FULL = "/*MODEL_FULL_PICKER_V1*/"
MARKER_TREAT = "/*MODEL_NO_TREATMENT_V1*/"
MARKER_NAMED = "/*MODEL_NAMED_VIEW_V1*/"
MARKER_CATALOG = "/*MODEL_CATALOG_V1*/"
MARKER_SHOW_MAX = "/*MODEL_SHOW_MAX_V1*/"

MAX_MEM_INJECT = 4
